image: ortussolutions/commandbox:alpine

stages:
  - build
  - test
  - deploy

build_app:
  stage: build
  script:
    - box install production=true

run_tests:
  stage: test
  only:
    - master
  # when: manual, always, on_success, on_failure
  script:
    - box install
    - box server start
    - box testbox run
